# Package building stuff - Set CPACK_GENERATOR to whatever package type
# you wish to build...
SET(CPACK_PACKAGE_VERSION "${KRISLIBRARY_VERSION}")
SET(CPACK_PACKAGE_VERSION_MAJOR "${KRISLIBRARY_MAJOR_VERSION}")
SET(CPACK_PACKAGE_VERSION_MINOR "${KRISLIBRARY_MINOR_VERSION}")
SET(CPACK_PACKAGE_VERSION_PATCH "${KRISLIBRARY_PATCH_VERSION}")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "CMake ${V_MAJOR}.${V_MINOR}")
SET(CPACK_PACKAGE_CONTACT "K. Hauser")
SET(CPACK_PACKAGE_VENDOR "Indiana University")
SET(CPACK_GENERATOR "DEB")
SET(CPACK_SOURCE_GENERATOR "TGZ")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME
  "${PROJECT_NAME}-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")

 # This must always be last statement!
INCLUDE(CPack)

