# Package building stuff - Set CPACK_GENERATOR to whatever package type
# you wish to build...
SET(CPACK_PACKAGE_VERSION "${KLAMPT_VERSION}")
SET(CPACK_PACKAGE_VERSION_MAJOR "${KLAMPT_MAJOR_VERSION}")
SET(CPACK_PACKAGE_VERSION_MINOR "${KLAMPT_MINOR_VERSION}")
SET(CPACK_PACKAGE_VERSION_PATCH "${KLAMPT_PATCH_VERSION}")
#SET(CPACK_PACKAGE_INSTALL_DIRECTORY "Klampt ${V_MAJOR}.${V_MINOR}")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "Klampt")
SET(CPACK_PACKAGE_CONTACT "Kris Hauser")
SET(CPACK_PACKAGE_VENDOR "University of Illinois")
IF(WIN32)
  SET(CPACK_GENERATOR "WIX")
  SET(CPACK_WIX_UPGRADE_GUID 6D28652E-751D-42F0-9D8A-44EAA79CB84B)
  SET(CPACK_WIX_LICENSE_RTF "${PROJECT_SOURCE_DIR}/dist/windows/license.rtf")
  SET(CPACK_WIX_UI_REF "WixUI_FeatureTree")
  SET(CPACK_SOURCE_GENERATOR "ZIP")
  SET(CPACK_SOURCE_PACKAGE_FILE_NAME
  "${PROJECT_NAME}-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
ELSE(WIN32)
  SET(CPACK_GENERATOR "DEB")
  SET(CPACK_SOURCE_GENERATOR "TGZ")
  SET(CPACK_SOURCE_PACKAGE_FILE_NAME
  "${PROJECT_NAME}-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
  SET(CPACK_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
  SET(CPACK_PACKAGING_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
  SET(CPACK_SET_DESTDIR TRUE)
ENDIF(WIN32)

set(CPACK_COMPONENT_APPS_DISPLAY_NAME "Klamp't Core Applications")
set(CPACK_COMPONENT_LIBRARIES_DISPLAY_NAME "Klamp't Static Library")
set(CPACK_COMPONENT_HEADERS_DISPLAY_NAME "C++ Headers")
set(CPACK_COMPONENTS_ALL apps libraries headers )

 # This must always be last statement!
INCLUDE(CPack)

