# Produces dependencies of Klampt
# Given KLAMPT_ROOT (optional)
# Produces
# - KLAMPT_LIBRARIES
# - KLAMPT_INCLUDE_DIRS
# - KLAMPT_DEFINITIONS

IF(NOT KLAMPT_ROOT)
  MESSAGE("KLAMPT_ROOT not defined, setting to .")
  SET(KLAMPT_ROOT .)
ENDIF( )

SET(KRISLIBRARY_ROOT "${KLAMPT_ROOT}/Library")
FIND_PACKAGE(KrisLibrary REQUIRED)
SET(KLAMPT_DEFINITIONS ${KRISLIBRARY_DEFINITIONS})
SET(KLAMPT_INCLUDE_DIRS ${KRISLIBRARY_INCLUDE_DIRS})
SET(KLAMPT_LIBRARIES ${KRISLIBRARY_LIBRARIES})

# ODE
SET(ODE_ROOT "${KLAMPT_ROOT}/Library/ode-0.11.1")
FIND_PACKAGE(ODE REQUIRED)
IF(ODE_FOUND)
  MESSAGE("Open Dynamics Engine library found")
  MESSAGE("  Compiler definitions: ${ODE_DEFINITIONS}") 
  SET(KLAMPT_DEFINITIONS ${KLAMPT_DEFINITIONS} ${ODE_DEFINITIONS})
  SET(KLAMPT_INCLUDE_DIRS ${KLAMPT_INCLUDE_DIRS} ${ODE_INCLUDE_DIRS})
  SET(KLAMPT_LIBRARIES ${KLAMPT_LIBRARIES} ${ODE_LIBRARIES})
ENDIF(ODE_FOUND)
