name: Build Python wheels on MacOS

on: 
  - push:
      paths-ignore:
        - '.github/actions/manylinux-wheels.yml'
        - 'Python/make_deps_linux.sh'
  - pull_request
  - workflow_dispatch

defaults:
  run:
    working-directory: Python

jobs:
  build_wheels:
    name: Build Python wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]

    steps:
      - uses: actions/checkout@v3

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

      # Used in `make_deps_macos.sh` in line `pip install cmake` and `check_mac_universal.py`
      - uses: actions/setup-python@v4

      - name: Build dependencies
        run: bash make_deps_macos.sh
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
          LDFLAGS: -framework OpenGL
      
      - name: Check universal build
        run: python check_mac_universal.py

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        with:
          package-dir: Python
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
          CIBW_ARCHS_MACOS: universal2
          LDFLAGS: -framework OpenGL

      - uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl