name: Build Python wheels on Manylinux 

on: [push, pull_request, workflow_dispatch]

defaults:
  run:
    working-directory: Python

jobs:
  build_wheels:
    name: Build Python wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v4

      #dependency building is in pyproject.toml
      #- name: Build dependencies
      #  run: bash make_deps_manylinux.sh

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        with:
          package-dir: Python
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"
      
      - uses: actions/upload-artifact@v3
        with:
          path: Python/wheelhouse/*.whl
